import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';
import ThemeClient from '@/components/ThemeClient';
import { AppBar } from '@/components';
import SessionProvider from '@/context/SessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-condensed',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${roboto.variable} font-condensed`}>
        <ThemeClient>
          <SessionProvider session={session as any}>
            <AppBar />
            {children}
          </SessionProvider>
        </ThemeClient>
      </body>
    </html>
  );
}
