import type { Metadata } from 'next';
import { Inter, Open_Sans, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import ThemeClient from '@/components/ThemeClient';
import { AppBar } from '@/components';

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-condensed',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-condensed`}>
        <ThemeClient>
          <AppBar />
          {children}
        </ThemeClient>
      </body>
    </html>
  );
}
